### ISSUE TITLE
Axe d'amélioration de la reconnaissance du mot clé

### ISSUE THREAD

**Issue by Seb85** [Spikharpax/Avatar-Client#1]
Bonjour Stéphane,

Je viens de tester l'outil Porcupine pour la détection du mot clé, une bonne alternative a la reconnaissance windows classique :

https://github.com/Picovoice/Porcupine

Peut être installé sous windows avec python. Je me suis créé un mot clé "Jarvis".
La reconnaissance est plus que correct.
Si tu as envie de tester ;)

Sinon des prévisions a venir?

**Comment by Spikharpax** [comment]
Slt Seb,

Ca m'a l'air intéressant oui, je connais. 
Je travaille sur stream-audio-fingerprint pour le client en ce moment mais porpucine est une autre bonne alternative que je vais regarder aussi.
Il faut que je mette en ligne une nouvelle version du serveur et un petit plugin de démo sympa pour faire des nodes à choix multiples. Ensuite on se focalisera sur un nouveau client.

A+ :-)

**Comment by J-Fawkes** [comment]
Bonjour Stéphane,

Je me permets de rebondir sur la conversation de Sébastien, qui ma fait découvrir le projet AVATAR récemment (merci, Seb pour cette belle découverte, et merci, Stéphane, pour ce beau projet).

Je voulais savoir s'il était envisageable d'ajouter une option.
(Comme le Loop Mode) permettent d'effectuer un réveil suivi de la commande. 
exemple:
Jarvis, il est quelle heure ? Au lieu de Jarvi.s --> oui, --> il est quelle heure ?

Une autre idée que je partage avec vous. Je cherche actuellement une solution pour récupérer l'information lorsque Avatar écoute ou non, cela afin d'activer un témoin lumineux.

Pour info nous discutons actuellement de l'éventualité de créer un forum afin de donner une autre impulsion au projet.
Qu'en penses-tu?

A+

**Comment by Spikharpax** [comment]
Bjr Quentin,

Bienvenue et merci :-)

Pour ta 1ère demande, malheureusement elle va à l'encontre du fonctionnement de l'application.
Ca s'explique...
La grammaire Windows  n'est utilisée que pour le mot-clé déclencheur. Ensuite, le WebKit API Google capture la règle. Le WebKit n'est pas en écoute continue, il ne se déclenche seulement que pour écouter et s’arrête ensuite. Pour réaliser ta demande, il faudrait donc que toutes les règles soient des grammaires Windows. Impossible pour le principe de fonctionnement d'AVATAR, le WebKit, le mode loop....

Pour le témoin lumineux, 
Je sais que je suis un peu "tatillon" mais justement, le fait d'avoir AVATAR qui te retourne une phrase quand il écoute te permet justement de savoir qu'il écoute... non ? ou alors quelque chose m'échappe...
Mais bon, si tu veux le faire, je pense qu'il faut chercher du coté client.
Il faudrait ajouter quelque chose entre les lignes 408 et 409 du fichier <client>/app/listen.js
setTimeout(function(){ 
     // AJOUTE UN TURN ON  ICI ...
    record(function(sentence) { 

Ensuite, il faut interrompre automatiquement si rien n'est dit:
ligne 410
if (!sentence) return reject("No sentence...");
à transformer en:
if (!sentence) {
   // AJOUTE UN TURN OFF ICI ...
   return reject("No sentence...");
}

Il faut aussi interrompre lorsque c'est terminé après les règles
Il faudrait ajouter quelque chose entre les lignes 305 et 306 du fichier <client>/app/listen.js
if (full == 'end') full = true;
 // AJOUTE UN TURN OFF ICI ...
// reset listen

Ce que tu dois ajouter en TURNON et TURNOFF doit être une règle d'un plugin coté serveur, quelque chose comme ca:
socket.emit('action', 'allume le témoin lumineux'); 
socket.emit('action', 'éteint le témoin lumineux');

Mais ce plugin en position 1 par un "nlpPosition":1 dans son fichier de properties pour qu'il vu rapidement et exécuté en 1er.

Je ne suis absolument pas contre un forum, si ca vous dit, n'hésitez pas :-)
je serais toujours là pour vous donner des infos.
